# Generated by Django 5.0.6 on 2026-10-08 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentTextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('health_data', 'Tratamiento de datos de salud'), ('ai_processing', 'Envío sin identificar a la inteligencia artificial')], max_length=20, verbose_name='Finalidad')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('body', models.TextField(verbose_name='Texto completo')),
                ('is_current', models.BooleanField(default=False, verbose_name='Vigente')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicada')),
            ],
            options={
                'verbose_name': 'Texto de consentimiento',
                'verbose_name_plural': 'Textos de consentimiento',
                'ordering': ['purpose', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Otorgado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Retirado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Clienta')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-granted_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='consenttextversion',
            constraint=models.UniqueConstraint(fields=('purpose', 'version'), name='health_consenttext_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='consenttextversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('purpose',), name='health_consenttext_one_current'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='text_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='health.consenttextversion', verbose_name='Texto aceptado'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'text_version'), name='health_consent_one_active_per_version'),
        ),
    ]
