# Generated by Django 5.0.6 on 2026-10-09 03:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_initial_consent_texts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('is_current', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada')),
                ('created_by_role', models.CharField(choices=[('member', 'Clienta'), ('trainer', 'Entrenador/a')], max_length=10, verbose_name='Rol de quien la creó')),
                ('confirmed_by_client_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada por la clienta')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sex_for_calculation', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NA', 'Prefiero no decir')], max_length=2, verbose_name='Sexo para el cálculo')),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Peso meta (kg)')),
                ('conditions', models.JSONField(blank=True, default=list, verbose_name='Condiciones')),
                ('condition_controlled', models.BooleanField(default=False, verbose_name='Condiciones controladas')),
                ('medical_clearance', models.BooleanField(default=False, verbose_name='Autorización médica')),
                ('clearance_date', models.DateField(blank=True, null=True, verbose_name='Fecha de la autorización médica')),
                ('medications', models.JSONField(blank=True, default=list, verbose_name='Medicamentos')),
                ('injuries', models.JSONField(blank=True, default=list, verbose_name='Lesiones')),
                ('recent_surgery', models.CharField(choices=[('none', 'Ninguna'), ('under_6m', 'Hace menos de 6 meses'), ('6_12m', 'Hace entre 6 y 12 meses'), ('over_12m', 'Hace más de 12 meses')], max_length=10, verbose_name='Cirugía reciente')),
                ('pregnancy_status', models.CharField(choices=[('none', 'Ninguno'), ('pregnant', 'Embarazo'), ('lactating', 'Lactancia'), ('postpartum_under_6m', 'Posparto de menos de 6 meses')], max_length=20, verbose_name='Embarazo o lactancia')),
                ('eating_disorder_history', models.CharField(choices=[('no', 'No'), ('yes', 'Sí'), ('prefer_not_say', 'Prefiero no decir')], max_length=15, verbose_name='Antecedentes de trastorno alimentario')),
                ('parq', models.JSONField(default=dict, verbose_name='Cuestionario de aptitud (q1..q7)')),
                ('other_condition_text', models.CharField(blank=True, max_length=300, verbose_name='Otra condición')),
                ('medications_text', models.CharField(blank=True, max_length=300, verbose_name='Medicamentos (texto)')),
                ('injuries_text', models.CharField(blank=True, max_length=300, verbose_name='Lesiones (texto)')),
                ('disliked_foods_text', models.CharField(blank=True, max_length=300, verbose_name='Alimentos que no le gustan')),
                ('liked_foods_text', models.CharField(blank=True, max_length=300, verbose_name='Alimentos que le gustan')),
                ('diet_type', models.CharField(choices=[('omnivore', 'Como de todo'), ('vegetarian', 'Vegetariana'), ('vegan', 'Vegana'), ('pescatarian', 'Pescetariana'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('other', 'Otra')], max_length=15, verbose_name='Tipo de dieta')),
                ('allergies', models.JSONField(blank=True, default=list, verbose_name='Alergias')),
                ('allergy_severity', models.CharField(blank=True, choices=[('mild', 'Leve o moderada'), ('anaphylaxis', 'Grave (puede causar anafilaxia)')], max_length=12, verbose_name='Gravedad de la alergia')),
                ('intolerances', models.JSONField(blank=True, default=list, verbose_name='Intolerancias')),
                ('meal_slots', models.JSONField(default=list, verbose_name='Comidas del día')),
                ('meal_times', models.JSONField(blank=True, default=dict, verbose_name='Horarios de las comidas')),
                ('cooking_access', models.CharField(choices=[('full', 'Puedo cocinar con todo lo necesario'), ('basic', 'Tengo lo básico para cocinar'), ('none', 'No puedo cocinar')], max_length=5, verbose_name='Posibilidad de cocinar')),
                ('budget_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=6, verbose_name='Presupuesto')),
                ('eats_out_per_week', models.PositiveSmallIntegerField(default=0, verbose_name='Comidas fuera por semana')),
                ('training_days_per_week', models.PositiveSmallIntegerField(verbose_name='Días de entrenamiento por semana')),
                ('session_minutes', models.PositiveSmallIntegerField(verbose_name='Minutos por sesión')),
                ('training_place', models.CharField(choices=[('gym', 'En el gimnasio'), ('home', 'En casa')], max_length=4, verbose_name='Lugar de entrenamiento')),
                ('equipment', models.JSONField(blank=True, default=list, verbose_name='Equipo disponible')),
                ('experience_level', models.CharField(choices=[('none', 'Nunca he entrenado'), ('beginner', 'Principiante'), ('intermediate', 'Intermedia'), ('advanced', 'Avanzada')], max_length=12, verbose_name='Experiencia')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentaria (casi no me muevo)'), ('light', 'Ligera (me muevo algo en el día)'), ('moderate', 'Moderada (activa casi todos los días)'), ('active', 'Activa (trabajo o rutina muy activa)')], max_length=9, verbose_name='Nivel de actividad')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Horas de sueño')),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='health.consentrecord', verbose_name='Autorización vigente al guardar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Clienta')),
            ],
            options={
                'verbose_name': 'Ficha de salud',
                'verbose_name_plural': 'Fichas de salud',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='HealthAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Consulta'), ('edit', 'Edición'), ('export', 'Descarga'), ('delete', 'Borrado')], max_length=10, verbose_name='Acción')),
                ('profile_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versión de la ficha')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cuándo')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_access_actions', to=settings.AUTH_USER_MODEL, verbose_name='Quién')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_access_log', to=settings.AUTH_USER_MODEL, verbose_name='Clienta')),
            ],
            options={
                'verbose_name': 'Acceso a la ficha de salud',
                'verbose_name_plural': 'Accesos a la ficha de salud',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='health_access_client_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='healthprofile',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='health_profile_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='healthprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='health_profile_one_current'),
        ),
    ]
