# Generated by Django 5.0.6 on 2026-05-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_users', to='memberships.membershipplan', verbose_name='Plan de interés'),
        ),
    ]
