# Generated by Django 5.0.6 on 2026-05-24 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador/a asignado/a'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Descripción breve del entrenador (aparece en la página Nosotros)', verbose_name='Descripción / Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='training_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Pérdida de peso'), ('muscle_gain', 'Ganancia muscular'), ('cardio', 'Resistencia cardiovascular'), ('rehab', 'Rehabilitación / Salud general'), ('sports', 'Rendimiento deportivo'), ('toning', 'Tonificación y definición')], default='', max_length=20, verbose_name='Meta de entrenamiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('trainer', 'Entrenador/a'), ('member', 'Miembro')], default='member', max_length=10, verbose_name='Rol'),
        ),
    ]
