[build]
builder = "nixpacks"

[build.env]
DJANGO_SETTINGS_MODULE = "config.settings.production"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
