# Generated by Django 5.0.6 on 2026-05-06 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routines', to=settings.AUTH_USER_MODEL, verbose_name='Entrenadora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del día')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='routines.routine', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Día de rutina',
                'verbose_name_plural': 'Días de rutina',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(verbose_name='Series')),
                ('reps', models.CharField(max_length=50, verbose_name='Repeticiones')),
                ('rest_seconds', models.PositiveIntegerField(verbose_name='Descanso (seg)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routineday', verbose_name='Día')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio en rutina',
                'verbose_name_plural': 'Ejercicios en rutina',
                'ordering': ['order'],
            },
        ),
    ]
