# Generated by Django 5.0.6 on 2026-10-08 18:08

import apps.exercises.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exercises/videos/', verbose_name='Video (archivo)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Pega el enlace de YouTube. Ej: https://youtu.be/abc123 o https://youtube.com/watch?v=abc123', validators=[apps.exercises.validators.validate_youtube_url], verbose_name='URL de video (YouTube)'),
        ),
    ]
