# Generated by Django 5.0.6 on 2026-05-06 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Estatura (m)')),
                ('goal', models.TextField(verbose_name='Objetivo')),
                ('physical_restrictions', models.TextField(blank=True, verbose_name='Restricciones físicas')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('imc_classification', models.CharField(blank=True, max_length=50, verbose_name='Clasificación IMC')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Entrenadora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Valoración inicial',
                'verbose_name_plural': 'Valoraciones iniciales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DixonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.PositiveIntegerField(verbose_name='Pulso en reposo (P1)')),
                ('p2', models.PositiveIntegerField(verbose_name='Pulso post-ejercicio (P2)')),
                ('p3', models.PositiveIntegerField(verbose_name='Pulso 1 min después (P3)')),
                ('index_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Índice Dixon')),
                ('classification', models.CharField(blank=True, max_length=100, verbose_name='Clasificación')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dixon_test', to='assessments.initialassessment', verbose_name='Valoración')),
            ],
            options={
                'verbose_name': 'Test de Dixon',
                'verbose_name_plural': 'Tests de Dixon',
            },
        ),
    ]
