# Generated by Django 5.0.6 on 2026-05-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_rename_dixon_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dixontest',
            options={'verbose_name': 'Test de Dickson', 'verbose_name_plural': 'Tests de Dickson'},
        ),
    ]
