# Generated by Django 5.0.6 on 2026-10-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_bodymeasurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dixontest',
            options={'verbose_name': 'Test de Ruffier-Dickson', 'verbose_name_plural': 'Tests de Ruffier-Dickson'},
        ),
    ]
