# Generated by Django 5.0.6 on 2026-10-08 21:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_dixontest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='body_fat_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('3')), django.core.validators.MaxValueValidator(Decimal('70'))], verbose_name='Grasa corporal (%)'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='hip_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30')), django.core.validators.MaxValueValidator(Decimal('300'))], verbose_name='Cadera (cm)'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='Revisar posible error'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='source',
            field=models.CharField(choices=[('trainer', 'Entrenador/a'), ('member', 'Clienta')], default='trainer', max_length=10, verbose_name='Registrada por'),
        ),
    ]
