# Generated by Django 5.0.6 on 2026-05-06 22:59

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=apps.payments.models._gen_reference, max_length=64, unique=True, verbose_name='Referencia interna')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='Monto en centavos (COP)')),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('voided', 'Anulado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=128, verbose_name='ID transacción Wompi')),
                ('payment_method_type', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('raw_webhook', models.JSONField(blank=True, null=True, verbose_name='Payload webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='memberships.membershipplan', verbose_name='Plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
