# Generated by Django 5.0.6 on 2026-10-08 18:00

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_manualpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.payments.models.receipt_upload_to, verbose_name='Comprobante (foto o PDF)'),
        ),
    ]
