# Generated by Django 5.0.6 on 2026-10-08 18:43

import apps.payments.models
import apps.payments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_receipt_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=apps.payments.storage.receipts_storage, upload_to=apps.payments.models.receipt_upload_to, verbose_name='Comprobante (foto o PDF)'),
        ),
    ]
